# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'homework3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'Kingfisher', '~> 7.0'
  # Pods for homework3

  target 'homework3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'homework3UITests' do
    # Pods for testing
  end

end
